### ISSUE TITLE
Why not use mongodb or Redis?

### ISSUE THREAD

**Issue by steve21124** [dangrossman/Bookmarkly#1]
Why not use mongodb or Redis?

**Comment by dangrossman** [comment]
Why not MySQL? :) Known schema, relational data, it fits the bill.

**Comment by asmuth** [comment]
Mh, what speaks against using MySQL? It's fast and very well documented and tested. Also, most of the users will probably have it installed already and a lot of distros/OS-es provide an installer/package. What would be the benefit of choosing redis or mongo over mysql?
