### ISSUE TITLE
screenshots.bookmarkly.com service

### ISSUE THREAD

**Issue by aabril** [dangrossman/Bookmarkly#4]
Is http://screenshots.bookmarkly.com another independent app?
I'm running bookmarkly locally and it's making requests to this url, and I wonder what app is.

Regards.

**Comment by dangrossman** [comment]
Yes, it's an independent app, a server running PhantomJS to take screenshots with Webkit. There's no easy way to package that up, it's always taken a ton of messing with and compiling dependencies to get running for me.

http://code.google.com/p/phantomjs/

**Comment by aabril** [comment]
Nice!
anyway I'll check PhantomJS. 
Thanks for the info.
