### ISSUE TITLE
express 2.5.6 error on node 0.8

### ISSUE THREAD

**Issue by ivanistheone** [dangrossman/Bookmarkly#5]
I get an error trying to install dependencies

```
824 info installOne express@2.5.6
825 error notsup Unsupported
825 error notsup Not compatible with your version of node/npm: express@2.5.6
825 error notsup Required: {"node":">= 0.4.1 < 0.7.0"}
825 error notsup Actual:   {"npm":"1.1.32","node":"0.8.0"}
826 error System Darwin 10.6.0
827 error command "node" "/usr/local/bin/npm" "install" "-d"
```

Should I switch to node 0.7 or can I modify the express version in package.json so it works?

**Comment by dangrossman** [comment]
I just built Node 0.8.16 and ran `npm install -d` and got a working Bookmarkly server up with no changes. Express 2.5.6 seems to work on Node 0.8 without issue.

https://gist.github.com/4332828

**Comment by ivanistheone** [comment]
Confirmed. Works with node 0.8.16. 

Sorry for mis-bug, I had node 0.8.0 on my machine. 

Thx for the quick reply!
