### ISSUE TITLE
please see it , thx

### ISSUE THREAD

**Issue by riskers** [dangrossman/Bookmarkly#9]
Hi ,
I notice the `EditView` used `save()` :

```
this.model.set({ url: url, title: title, description: description, tags: tags, timestamp: Math.round(new Date().getTime() / 1000) });
this.model.save();
```

then,the data post to server is string json :

```
{url: "http://123", title: "123", description: "123", tags: [], timestamp: 1435309038}
```

I want to know your server how to deal this string json , because i only know how to deal such data:

```
url=http://123&title=123&description=123&tags=null&timestamp=1435309038
```

how to deal data in `save()` of Backbone ? this question puzzle me so long time .
please answer me , thanks

**Comment by dangrossman** [comment]
https://github.com/dangrossman/Bookmarkly/blob/master/server.js#L373

That's a JSON string, and since the server is written in JavaScript, that string can be treated like any JavaScript object.
